### ISSUE TITLE
Enable creating of non-active versions

### ISSUE THREAD

**Issue by fstehle** [Jimdo/ansible-fastly#2]
in order to test changes when using it for a service, which was clicked before.

Maybe add an `activate_new_version` parameter for this:
```
- fastly_service:
    name: Example service
    activate_new_version: true
    domains:
      - name: test1.example.net
        comment: test1
      - name: test2.example.net
        comment: test2
    ...
```
